let colors = {
    transparent: "transparent",

    primary: {
        default: "var(--color-primary)",
        dark: "var(--color-primary-secondary)",
        light: "var(--color-primary-tertiary)",
    },

    background: {
        default: "var(--color-background)",
        secondary: "var(--color-background-secondary)",
    },

    dark: "var(--color-dark)",
    black: "var(--color-black)",
    white: "var(--color-white)",

    gray: {
        100: "var(--color-gray-100)",
        200: "var(--color-gray-200)",
        300: "var(--color-gray-300)",
        400: "var(--color-gray-400)",
        500: "var(--color-gray-500)",
        600: "var(--color-gray-600)",
        700: "var(--color-gray-700)",
        800: "var(--color-gray-700)",
        900: "var(--color-gray-900)",
    },
    red: {
        100: "var(--color-red-100)",
        200: "var(--color-red-200)",
        300: "var(--color-red-300)",
        400: "var(--color-red-400)",
        500: "var(--color-red-500)",
        600: "var(--color-red-600)",
        700: "var(--color-red-700)",
        800: "var(--color-red-700)",
        900: "var(--color-red-900)",
    },
    orange: {
        100: "var(--color-orange-100)",
        200: "var(--color-orange-200)",
        300: "var(--color-orange-300)",
        400: "var(--color-orange-400)",
        500: "var(--color-orange-500)",
        600: "var(--color-orange-600)",
        700: "var(--color-orange-700)",
        800: "var(--color-orange-700)",
        900: "var(--color-orange-900)",
    },
    yellow: {
        100: "var(--color-yellow-100)",
        200: "var(--color-yellow-200)",
        300: "var(--color-yellow-300)",
        400: "var(--color-yellow-400)",
        500: "var(--color-yellow-500)",
        600: "var(--color-yellow-600)",
        700: "var(--color-yellow-700)",
        800: "var(--color-yellow-700)",
        900: "var(--color-yellow-900)",
    },
    green: {
        100: "var(--color-green-100)",
        200: "var(--color-green-200)",
        300: "var(--color-green-300)",
        400: "var(--color-green-400)",
        500: "var(--color-green-500)",
        600: "var(--color-green-600)",
        700: "var(--color-green-700)",
        800: "var(--color-green-700)",
        900: "var(--color-green-900)",
    },
    teal: {
        100: "var(--color-teal-100)",
        200: "var(--color-teal-200)",
        300: "var(--color-teal-300)",
        400: "var(--color-teal-400)",
        500: "var(--color-teal-500)",
        600: "var(--color-teal-600)",
        700: "var(--color-teal-700)",
        800: "var(--color-teal-700)",
        900: "var(--color-teal-900)",
    },
    blue: {
        100: "var(--color-blue-100)",
        200: "var(--color-blue-200)",
        300: "var(--color-blue-300)",
        400: "var(--color-blue-400)",
        500: "var(--color-blue-500)",
        600: "var(--color-blue-600)",
        700: "var(--color-blue-700)",
        800: "var(--color-blue-700)",
        900: "var(--color-blue-900)",
    },
    indigo: {
        100: "var(--color-indigo-100)",
        200: "var(--color-indigo-200)",
        300: "var(--color-indigo-300)",
        400: "var(--color-indigo-400)",
        500: "var(--color-indigo-500)",
        600: "var(--color-indigo-600)",
        700: "var(--color-indigo-700)",
        800: "var(--color-indigo-700)",
        900: "var(--color-indigo-900)",
    },
    purple: {
        100: "var(--color-purple-100)",
        200: "var(--color-purple-200)",
        300: "var(--color-purple-300)",
        400: "var(--color-purple-400)",
        500: "var(--color-purple-500)",
        600: "var(--color-purple-600)",
        700: "var(--color-purple-700)",
        800: "var(--color-purple-700)",
        900: "var(--color-purple-900)",
    },
    pink: {
        100: "var(--color-pink-100)",
        200: "var(--color-pink-200)",
        300: "var(--color-pink-300)",
        400: "var(--color-pink-400)",
        500: "var(--color-pink-500)",
        600: "var(--color-pink-600)",
        700: "var(--color-pink-700)",
        800: "var(--color-pink-700)",
        900: "var(--color-pink-900)",
    },
}

module.exports = {
    prefix: "",
    important: false,
    separator: ":",
    theme: {
        screens: {
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1280px",
        },
        colors,
        spacing: {
            px: "1px",
            "0": "0",
            "1": "0.25rem",
            "2": "0.5rem",
            "3": "0.75rem",
            "4": "1rem",
            "5": "1.25rem",
            "6": "1.5rem",
            "8": "2rem",
            "10": "2.5rem",
            "12": "3rem",
            "16": "4rem",
            "20": "5rem",
            "24": "6rem",
            "32": "8rem",
            "40": "10rem",
            "48": "12rem",
            "56": "14rem",
            "64": "16rem",
            "72": "20rem",
            "120": "30rem",
        },
        backgroundColor: theme => theme("colors"),
        backgroundOpacity: theme => theme('opacity'),
        backgroundPosition: {
            bottom: "bottom",
            center: "center",
            left: "left",
            "left-bottom": "left bottom",
            "left-top": "left top",
            right: "right",
            "right-bottom": "right bottom",
            "right-top": "right top",
            top: "top",
        },
        backgroundSize: {
            auto: "auto",
            cover: "cover",
            contain: "contain",
        },
        borderColor: theme => ({
            ...theme("colors"),
            default: theme("colors.gray.300", "currentColor"),
        }),
        borderRadius: {
            none: "0",
            sm: "0.125rem",
            default: "0.25rem",
            md: "0.375rem",
            lg: "0.5rem",
            full: "9999px",
        },
        borderWidth: {
            default: "1px",
            "0": "0",
            "2": "2px",
            "4": "4px",
            "8": "8px",
        },
        boxShadow: {
            sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
            default:
                "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
            md:
                "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
            lg:
                "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
            xl:
                "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
            "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
            inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
            outline: "0 0 0 3px rgba(66, 153, 225, 0.5)",
            none: "none",
        },
        container: {},
        cursor: {
            auto: "auto",
            default: "default",
            pointer: "pointer",
            wait: "wait",
            text: "text",
            move: "move",
            "not-allowed": "not-allowed",
        },
        fill: {
            current: "currentColor",
        },
        flex: {
            "1": "1 1 0%",
            auto: "1 1 auto",
            initial: "0 1 auto",
            none: "none",
        },
        flexGrow: {
            "0": "0",
            default: "1",
        },
        flexShrink: {
            "0": "0",
            default: "1",
        },
        fontFamily: {
            sans: [
                "Inter",
                '"Source Sans Pro"',
                "-apple-system",
                "BlinkMacSystemFont",
                '"Segoe UI"',
                "Roboto",
                '"Helvetica Neue"',
                "Arial",
                '"Noto Sans"',
                "sans-serif",
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            serif: [
                "Georgia",
                "Cambria",
                '"Times New Roman"',
                "Times",
                "serif",
            ],
            mono: [
                "Menlo",
                "Monaco",
                "Consolas",
                '"Liberation Mono"',
                '"Courier New"',
                "monospace",
            ],
        },
        fontSize: {
            "2xs": "0.65rem",
            xs: "0.8rem",
            sm: "0.95rem",
            base: "1rem",
            md: "1.05rem",
            lg: "1.2rem",
            xl: "1.35rem",
            "2xl": "1.5rem",
            "3xl": "1.875rem",
            "4xl": "2.25rem",
            "5xl": "3rem",
            "6xl": "4rem",
        },
        fontWeight: {
            hairline: "100",
            thin: "200",
            light: "300",
            normal: "400",
            medium: "500",
            semibold: "600",
            bold: "700",
            extrabold: "800",
            black: "900",
        },
        height: theme => ({
            auto: "auto",
            ...theme("spacing"),
            full: "100%",
            screen: "100vh",
        }),
        inset: {
            "0": "0",
            auto: "auto",
        },
        letterSpacing: {
            tighter: "-0.05em",
            tight: "-0.025em",
            normal: "0",
            wide: "0.025em",
            wider: "0.05em",
            widest: "0.1em",
        },
        lineHeight: {
            none: "1",
            tight: "1.25",
            snug: "1.375",
            normal: "1.5",
            relaxed: "1.625",
            loose: "2",
        },
        listStyleType: {
            none: "none",
            disc: "disc",
            decimal: "decimal",
        },
        margin: (theme, { negative }) => ({
            auto: "auto",
            ...theme("spacing"),
            ...negative(theme("spacing")),
        }),
        maxHeight: {
            xxs: "12rem",
            full: "100%",
            "80vh": "80vh",
            screen: "100vh",
        },
        maxWidth: theme => ({
            xxs: "14rem",
            xs: "20rem",
            sm: "24rem",
            md: "28rem",
            lg: "32rem",
            xl: "36rem",
            "2xl": "42rem",
            "3xl": "48rem",
            "4xl": "56rem",
            "5xl": "64rem",
            "6xl": "72rem",
            full: "100%",
            "screen-sm": theme("screens.sm"),
            "screen-md": theme("screens.md"),
            "screen-lg": theme("screens.lg"),
            "screen-xl": theme("screens.xl"),
        }),
        minHeight: theme => ({
            ...theme("spacing"),
            "0": "0",
            md: "28rem",
            full: "100%",
            screen: "100vh",
        }),
        minWidth: {
            "0": "0",
            xs: "20rem",
            sm: "24rem",
            md: "28rem",
            lg: "32rem",
            xl: "36rem",
            "2xl": "42rem",
            "3xl": "48rem",
            "4xl": "56rem",
            "5xl": "64rem",
            "6xl": "72rem",
            full: "100%",
        },
        objectPosition: {
            bottom: "bottom",
            center: "center",
            left: "left",
            "left-bottom": "left bottom",
            "left-top": "left top",
            right: "right",
            "right-bottom": "right bottom",
            "right-top": "right top",
            top: "top",
        },
        opacity: {
            "0": "0",
            "25": "0.25",
            "50": "0.5",
            "75": "0.75",
            "100": "1",
        },
        order: {
            first: "-9999",
            last: "9999",
            none: "0",
            "1": "1",
            "2": "2",
            "3": "3",
            "4": "4",
            "5": "5",
            "6": "6",
            "7": "7",
            "8": "8",
            "9": "9",
            "10": "10",
            "11": "11",
            "12": "12",
        },
        padding: theme => theme("spacing"),
        placeholderColor: theme => theme("colors"),
        stroke: {
            current: "currentColor",
        },
        textColor: theme => theme("colors"),
        width: theme => ({
            auto: "auto",
            ...theme("spacing"),
            "1/2": "50%",
            "1/3": "33.333333%",
            "2/3": "66.666667%",
            "1/4": "25%",
            "2/4": "50%",
            "3/4": "75%",
            "1/5": "20%",
            "2/5": "40%",
            "3/5": "60%",
            "4/5": "80%",
            "1/6": "16.666667%",
            "2/6": "33.333333%",
            "3/6": "50%",
            "4/6": "66.666667%",
            "5/6": "83.333333%",
            "1/12": "8.333333%",
            "2/12": "16.666667%",
            "3/12": "25%",
            "4/12": "33.333333%",
            "5/12": "41.666667%",
            "6/12": "50%",
            "7/12": "58.333333%",
            "8/12": "66.666667%",
            "9/12": "75%",
            "10/12": "83.333333%",
            "11/12": "91.666667%",
            full: "100%",
            screen: "100vw",
        }),
        zIndex: {
            auto: "auto",
            "-1": "-1",
            "0": "0",
            "1": "1",
            "10": "10",
            "20": "20",
            "30": "30",
            "40": "40",
            "50": "50",
        },
    },
    variants: {
        accessibility: ["responsive", "focus"],
        alignContent: ["responsive"],
        alignItems: ["responsive"],
        alignSelf: ["responsive"],
        appearance: ["responsive"],
        backgroundAttachment: ["responsive"],
        backgroundColor: ["responsive", "hover", "focus"],
        backgroundOpacity: ['responsive', 'hover', 'focus'],
        backgroundPosition: ["responsive"],
        backgroundRepeat: ["responsive"],
        backgroundSize: ["responsive"],
        borderCollapse: ["responsive"],
        borderColor: ["responsive", "hover", "focus"],
        borderRadius: ["responsive"],
        borderStyle: ["responsive"],
        borderWidth: ["responsive"],
        boxShadow: ["responsive", "hover", "focus"],
        cursor: ["responsive"],
        display: ["responsive"],
        fill: ["responsive"],
        flex: ["responsive"],
        flexDirection: ["responsive"],
        flexGrow: ["responsive"],
        flexShrink: ["responsive"],
        flexWrap: ["responsive"],
        float: ["responsive"],
        fontFamily: ["responsive"],
        fontSize: ["responsive"],
        fontSmoothing: ["responsive"],
        fontStyle: ["responsive"],
        fontWeight: ["responsive", "hover", "focus"],
        height: ["responsive"],
        inset: ["responsive"],
        justifyContent: ["responsive"],
        letterSpacing: ["responsive"],
        lineHeight: ["responsive"],
        listStylePosition: ["responsive"],
        listStyleType: ["responsive"],
        margin: ["responsive"],
        maxHeight: ["responsive"],
        maxWidth: ["responsive"],
        minHeight: ["responsive"],
        minWidth: ["responsive"],
        objectFit: ["responsive"],
        objectPosition: ["responsive"],
        opacity: ["responsive", "hover", "focus"],
        order: ["responsive"],
        outline: ["responsive", "focus"],
        overflow: ["responsive"],
        padding: ["responsive"],
        placeholderColor: ["responsive", "focus"],
        pointerEvents: ["responsive"],
        position: ["responsive"],
        resize: ["responsive"],
        stroke: ["responsive"],
        tableLayout: ["responsive"],
        textAlign: ["responsive"],
        textColor: ["responsive", "hover", "focus"],
        textDecoration: ["responsive", "hover", "focus"],
        textTransform: ["responsive"],
        userSelect: ["responsive"],
        verticalAlign: ["responsive"],
        visibility: ["responsive"],
        whitespace: ["responsive"],
        width: ["responsive"],
        wordBreak: ["responsive"],
        zIndex: ["responsive"],
    },
    corePlugins: {
        float: false,
    },
    plugins: [],
}
