name: Deploy Dapp

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    env:
      VITE_APP_NAME: "Etherna"
      VITE_APP_TAGLINE: "A transparent video platform"
      VITE_APP_VERIFIED_ORIGINS: "etherna.io"
      VITE_APP_FEEDBACK_URL: "https://etherna.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-T/-m454we/b/23/a44af77267a987a660377e5c46e0fb64/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=1c189ede"
      VITE_APP_INDEX_URL: "https://index.etherna.io/api/v0.2"
      VITE_APP_GATEWAY_URL: "https://gateway.etherna.io/api/v0.2"
      VITE_APP_CREDIT_URL: "https://credit.etherna.io"
      VITE_APP_AUTH_URL: "https://sso.etherna.io/api/v0.2"
      VITE_APP_POSTAGE_URL: "https://gateway.etherna.io/api/v0.2/stamps"
      GENERATE_SOURCEMAP: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Build react app
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        architecture: 'x64'
    - run: yarn install --ignore-optional
    - run: yarn build
    - name: Upload to Host
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: build
        remoteDir: ${{ secrets.REMOTE_DIR }}
        options: "--delete -X cgi-bin/ -X .well-known/"
    - name: Upload to Swarm
      uses: Etherna/swarm-upload-action@0.2
      with:
        localRoot: build
        defaultPath: index.html
        feedName: EthernaDapp
        feedUserPrivateKey: ${{ secrets.PRIVATE_KEY }}
