name: Deploy Dapp

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    env:
      REACT_APP_NAME: "Etherna"
      REACT_APP_TAGLINE: "A transparent video platform"
      REACT_APP_INFURA_ID: ${{ secrets.INFURA_ID }}
      REACT_APP_INDEX_HOST: "https://index.etherna.io"
      REACT_APP_INDEX_API_PATH: "/api/v0.2"
      REACT_APP_GATEWAY_HOST: "https://gateway.etherna.io"
      GENERATE_SOURCEMAP: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Build react app
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn build
    - name: Upload to Host
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: build
        remoteDir: ${{ secrets.REMOTE_DIR }}
    - name: Upload to Swarm
      uses: Etherna/swarm-upload-action@0.2
      with:
        localRoot: build
        defaultPath: index.html
        feedName: EthernaVideoDapp
        feedUserPrivateKey: ${{ secrets.PRIVATE_KEY }}
